# Generated by Django 5.1.1 on 2024-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default_img/img.png', upload_to='user_images/'),
        ),
    ]
