# Generated by Django 5.1.1 on 2024-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheravailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='day_of_week',
            field=models.ManyToManyField(blank=True, related_name='work_days', to='additions.dayofweek'),
        ),
    ]
